// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Effi-Support",
            "url": "https://www.effiware.com/contact",
            "email": "contact@effiware.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/clicks": {
            "get": {
                "description": "Total number of clicks recorded in the system",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clicks"
                ],
                "summary": "Get the number of clicks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Clicks"
                        }
                    }
                }
            }
        },
        "/clicks/increment": {
            "post": {
                "description": "Increment the click total by one and return the new value",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clicks"
                ],
                "summary": "Increment the number of clicks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Clicks"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "200 when Postgres and Redis are reachable and the instance is not draining; 503 otherwise.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "ready",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "draining or a dependency is unreachable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Clicks": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 17
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "GOTH Template API",
	Description:      "JSON API of the GOTH stack template.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
