// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clicks.sql

package db

import (
	"context"
)

const getClickCount = `-- name: GetClickCount :one
SELECT count FROM clicks WHERE name = $1
`

func (q *Queries) GetClickCount(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, getClickCount, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementClickCount = `-- name: IncrementClickCount :one
UPDATE clicks SET count = count + 1
WHERE name = $1
RETURNING count
`

// Atomic read-modify-write: the returned value is this caller's own increment.
func (q *Queries) IncrementClickCount(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, incrementClickCount, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}
