// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const snapshotOrganizationHistory = `-- name: SnapshotOrganizationHistory :exec

INSERT INTO organizations_history (
    id, name, display_name, url, domains, attributes, realm_id, realm_name,
    created_at, modified_at, modified_by,
    version, changed_by, change_note
)
SELECT
    o.id, o.name, o.display_name, o.url, o.domains, o.attributes, o.realm_id, o.realm_name,
    o.created_at, o.modified_at, o.modified_by,
    (SELECT COALESCE(MAX(h.version), 0) + 1 FROM organizations_history h WHERE h.id = o.id),
    $1, $2
FROM organizations o
WHERE o.id = $3
`

type SnapshotOrganizationHistoryParams struct {
	ChangedBy  string      `json:"changed_by"`
	ChangeNote pgtype.Text `json:"change_note"`
	ID         pgtype.UUID `json:"id"`
}

// Audit-trail history writes. Every query here is called app-level inside the
// same tx as the base-row mutation (see SnapshotEntity in history.go); the
// version is self-computed as MAX+1, race-safe under the mutation's row lock.
func (q *Queries) SnapshotOrganizationHistory(ctx context.Context, arg SnapshotOrganizationHistoryParams) error {
	_, err := q.db.Exec(ctx, snapshotOrganizationHistory, arg.ChangedBy, arg.ChangeNote, arg.ID)
	return err
}

const snapshotTeamHistory = `-- name: SnapshotTeamHistory :exec
INSERT INTO teams_history (
    id, organization_id, type, name, description, tags, primary_color, secondary_color,
    created_at, modified_at, modified_by,
    version, changed_by, change_note
)
SELECT
    t.id, t.organization_id, t.type, t.name, t.description, t.tags, t.primary_color, t.secondary_color,
    t.created_at, t.modified_at, t.modified_by,
    (SELECT COALESCE(MAX(h.version), 0) + 1 FROM teams_history h WHERE h.id = t.id),
    $1, $2
FROM teams t
WHERE t.id = $3
`

type SnapshotTeamHistoryParams struct {
	ChangedBy  string      `json:"changed_by"`
	ChangeNote pgtype.Text `json:"change_note"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) SnapshotTeamHistory(ctx context.Context, arg SnapshotTeamHistoryParams) error {
	_, err := q.db.Exec(ctx, snapshotTeamHistory, arg.ChangedBy, arg.ChangeNote, arg.ID)
	return err
}
