// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type TeamMemberType string

const (
	TeamMemberTypeOwner  TeamMemberType = "owner"
	TeamMemberTypeMember TeamMemberType = "member"
	TeamMemberTypeViewer TeamMemberType = "viewer"
)

func (e *TeamMemberType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeamMemberType(s)
	case string:
		*e = TeamMemberType(s)
	default:
		return fmt.Errorf("unsupported scan type for TeamMemberType: %T", src)
	}
	return nil
}

type NullTeamMemberType struct {
	TeamMemberType TeamMemberType `json:"team_member_type"`
	Valid          bool           `json:"valid"` // Valid is true if TeamMemberType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeamMemberType) Scan(value interface{}) error {
	if value == nil {
		ns.TeamMemberType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeamMemberType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeamMemberType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeamMemberType), nil
}

type TeamType string

const (
	TeamTypeRegular TeamType = "regular"
	TeamTypeCustom  TeamType = "custom"
)

func (e *TeamType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeamType(s)
	case string:
		*e = TeamType(s)
	default:
		return fmt.Errorf("unsupported scan type for TeamType: %T", src)
	}
	return nil
}

type NullTeamType struct {
	TeamType TeamType `json:"team_type"`
	Valid    bool     `json:"valid"` // Valid is true if TeamType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeamType) Scan(value interface{}) error {
	if value == nil {
		ns.TeamType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeamType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeamType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeamType), nil
}

type WebhookType string

const (
	WebhookTypeGeneric WebhookType = "generic"
	WebhookTypeOther   WebhookType = "other"
)

func (e *WebhookType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookType(s)
	case string:
		*e = WebhookType(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookType: %T", src)
	}
	return nil
}

type NullWebhookType struct {
	WebhookType WebhookType `json:"webhook_type"`
	Valid       bool        `json:"valid"` // Valid is true if WebhookType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookType) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookType), nil
}

type Click struct {
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

type Organization struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	DisplayName pgtype.Text        `json:"display_name"`
	Url         pgtype.Text        `json:"url"`
	Domains     []string           `json:"domains"`
	Attributes  []byte             `json:"attributes"`
	RealmID     pgtype.UUID        `json:"realm_id"`
	RealmName   string             `json:"realm_name"`
	LastEventAt pgtype.Timestamptz `json:"last_event_at"`
	CreatedAt   time.Time          `json:"created_at"`
	ModifiedAt  pgtype.Timestamptz `json:"modified_at"`
	ModifiedBy  pgtype.Text        `json:"modified_by"`
}

type OrganizationMember struct {
	UserID            pgtype.UUID        `json:"user_id"`
	OrganizationID    pgtype.UUID        `json:"organization_id"`
	OrganizationRoles []string           `json:"organization_roles"`
	CreatedAt         time.Time          `json:"created_at"`
	ModifiedAt        pgtype.Timestamptz `json:"modified_at"`
	ModifiedBy        pgtype.Text        `json:"modified_by"`
}

type OrganizationsHistory struct {
	ID          pgtype.UUID        `json:"id"`
	Version     int32              `json:"version"`
	Name        string             `json:"name"`
	DisplayName pgtype.Text        `json:"display_name"`
	Url         pgtype.Text        `json:"url"`
	Domains     []string           `json:"domains"`
	Attributes  []byte             `json:"attributes"`
	RealmID     pgtype.UUID        `json:"realm_id"`
	RealmName   string             `json:"realm_name"`
	CreatedAt   time.Time          `json:"created_at"`
	ModifiedAt  pgtype.Timestamptz `json:"modified_at"`
	ModifiedBy  pgtype.Text        `json:"modified_by"`
	ChangedAt   time.Time          `json:"changed_at"`
	ChangedBy   string             `json:"changed_by"`
	ChangeNote  pgtype.Text        `json:"change_note"`
}

type Team struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Type           TeamType           `json:"type"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	Tags           []string           `json:"tags"`
	PrimaryColor   string             `json:"primary_color"`
	SecondaryColor string             `json:"secondary_color"`
	CreatedAt      time.Time          `json:"created_at"`
	ModifiedAt     pgtype.Timestamptz `json:"modified_at"`
	ModifiedBy     pgtype.Text        `json:"modified_by"`
}

type TeamMember struct {
	UserID     pgtype.UUID        `json:"user_id"`
	TeamID     pgtype.UUID        `json:"team_id"`
	MemberType TeamMemberType     `json:"member_type"`
	CreatedAt  time.Time          `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	ModifiedBy pgtype.Text        `json:"modified_by"`
}

type TeamsHistory struct {
	ID             pgtype.UUID        `json:"id"`
	Version        int32              `json:"version"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Type           TeamType           `json:"type"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	Tags           []string           `json:"tags"`
	PrimaryColor   string             `json:"primary_color"`
	SecondaryColor string             `json:"secondary_color"`
	CreatedAt      time.Time          `json:"created_at"`
	ModifiedAt     pgtype.Timestamptz `json:"modified_at"`
	ModifiedBy     pgtype.Text        `json:"modified_by"`
	ChangedAt      time.Time          `json:"changed_at"`
	ChangedBy      string             `json:"changed_by"`
	ChangeNote     pgtype.Text        `json:"change_note"`
}

type TechServiceRun struct {
	ServiceName    string             `json:"service_name"`
	LastStartedAt  time.Time          `json:"last_started_at"`
	LastFinishedAt pgtype.Timestamptz `json:"last_finished_at"`
	LastStatus     string             `json:"last_status"`
	LastError      pgtype.Text        `json:"last_error"`
	DurationMs     pgtype.Int8        `json:"duration_ms"`
	Details        []byte             `json:"details"`
}

type TechWebhook struct {
	Name              string             `json:"name"`
	ExternalID        string             `json:"external_id"`
	Url               string             `json:"url"`
	Type              WebhookType        `json:"type"`
	Enabled           bool               `json:"enabled"`
	Details           []byte             `json:"details"`
	LastSyncedAt      time.Time          `json:"last_synced_at"`
	LastOperationType pgtype.Text        `json:"last_operation_type"`
	LastUsedAt        pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt         time.Time          `json:"created_at"`
	CreatedBy         string             `json:"created_by"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	UserName     string             `json:"user_name"`
	Email        pgtype.Text        `json:"email"`
	Enabled      bool               `json:"enabled"`
	FirstName    pgtype.Text        `json:"first_name"`
	LastName     pgtype.Text        `json:"last_name"`
	Groups       []string           `json:"groups"`
	Attributes   []byte             `json:"attributes"`
	CreatedAt    time.Time          `json:"created_at"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	ModifiedAt   pgtype.Timestamptz `json:"modified_at"`
	ModifiedBy   pgtype.Text        `json:"modified_by"`
}
