// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetClickCount(ctx context.Context, name string) (int64, error)
	// Atomic read-modify-write: the returned value is this caller's own increment.
	IncrementClickCount(ctx context.Context, name string) (int64, error)
	// Gate check for services.RunIfDue: true when the named service last started
	// within the freshness window. now() is evaluated DB-side, which takes the
	// reader's clock out of the comparison; last_started_at is still stamped from
	// the writing instance's clock (RecordRun), so cross-instance skew eats into
	// the freshness slack — acceptable with NTP-synced hosts, where skew is far
	// below the 10% slack. last_started_at (not finished) keeps the effective
	// cadence start-to-start.
	IsServiceRunFresh(ctx context.Context, arg IsServiceRunFreshParams) (bool, error)
	ListServiceRuns(ctx context.Context) ([]TechServiceRun, error)
	// Audit-trail history writes. Every query here is called app-level inside the
	// same tx as the base-row mutation (see SnapshotEntity in history.go); the
	// version is self-computed as MAX+1, race-safe under the mutation's row lock.
	SnapshotOrganizationHistory(ctx context.Context, arg SnapshotOrganizationHistoryParams) error
	SnapshotTeamHistory(ctx context.Context, arg SnapshotTeamHistoryParams) error
	UpsertServiceRun(ctx context.Context, arg UpsertServiceRunParams) error
}

var _ Querier = (*Queries)(nil)
