// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_runs.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const isServiceRunFresh = `-- name: IsServiceRunFresh :one
SELECT EXISTS (
    SELECT 1 FROM tech_service_runs
    WHERE service_name = $1
      AND last_started_at > now() - make_interval(secs => $2::float8)
) AS fresh
`

type IsServiceRunFreshParams struct {
	ServiceName      string  `json:"service_name"`
	FreshnessSeconds float64 `json:"freshness_seconds"`
}

// Gate check for services.RunIfDue: true when the named service last started
// within the freshness window. now() is evaluated DB-side, which takes the
// reader's clock out of the comparison; last_started_at is still stamped from
// the writing instance's clock (RecordRun), so cross-instance skew eats into
// the freshness slack — acceptable with NTP-synced hosts, where skew is far
// below the 10% slack. last_started_at (not finished) keeps the effective
// cadence start-to-start.
func (q *Queries) IsServiceRunFresh(ctx context.Context, arg IsServiceRunFreshParams) (bool, error) {
	row := q.db.QueryRow(ctx, isServiceRunFresh, arg.ServiceName, arg.FreshnessSeconds)
	var fresh bool
	err := row.Scan(&fresh)
	return fresh, err
}

const listServiceRuns = `-- name: ListServiceRuns :many
SELECT service_name, last_started_at, last_finished_at, last_status, last_error, duration_ms, details FROM tech_service_runs
ORDER BY service_name
`

func (q *Queries) ListServiceRuns(ctx context.Context) ([]TechServiceRun, error) {
	rows, err := q.db.Query(ctx, listServiceRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TechServiceRun
	for rows.Next() {
		var i TechServiceRun
		if err := rows.Scan(
			&i.ServiceName,
			&i.LastStartedAt,
			&i.LastFinishedAt,
			&i.LastStatus,
			&i.LastError,
			&i.DurationMs,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertServiceRun = `-- name: UpsertServiceRun :exec
INSERT INTO tech_service_runs (
    service_name, last_started_at, last_finished_at, last_status, last_error, duration_ms, details
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) ON CONFLICT (service_name) DO UPDATE SET
    last_started_at  = excluded.last_started_at,
    last_finished_at = excluded.last_finished_at,
    last_status      = excluded.last_status,
    last_error       = excluded.last_error,
    duration_ms      = excluded.duration_ms,
    details          = excluded.details
`

type UpsertServiceRunParams struct {
	ServiceName    string             `json:"service_name"`
	LastStartedAt  time.Time          `json:"last_started_at"`
	LastFinishedAt pgtype.Timestamptz `json:"last_finished_at"`
	LastStatus     string             `json:"last_status"`
	LastError      pgtype.Text        `json:"last_error"`
	DurationMs     pgtype.Int8        `json:"duration_ms"`
	Details        []byte             `json:"details"`
}

func (q *Queries) UpsertServiceRun(ctx context.Context, arg UpsertServiceRunParams) error {
	_, err := q.db.Exec(ctx, upsertServiceRun,
		arg.ServiceName,
		arg.LastStartedAt,
		arg.LastFinishedAt,
		arg.LastStatus,
		arg.LastError,
		arg.DurationMs,
		arg.Details,
	)
	return err
}
