// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/effiware/goth-template/internal/views/components"

// pageHead is the shared <head>: meta, favicon, tailwind, htmx (+ its response
// handling config), alpine. Assets are served locally — no CDN, so the CSP in
// middlewares/security.go stays tight.
func pageHead(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/index.templ`, Line: 11, Col: 15}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><link href=\"/static/img/favicon.ico\" type=\"image/x-icon\" rel=\"icon\"><link href=\"/static/css/tailwind.css\" rel=\"stylesheet\"><script src=\"/static/js/htmx-2.0.10/htmx.min.js\"></script><!-- Keep in sync with hda.WithHTMLFallback: a status not listed here is\n\t     dropped by htmx instead of swapping the error fragment. The catch-all\n\t     MUST keep \"error\":true so failures never report as successful. --><meta name=\"htmx-config\" content='{\"responseHandling\": [{\"code\":\"204\",\"swap\":false},{\"code\":\"[23]..\",\"swap\":true},{\"code\":\"403\",\"swap\":true,\"error\":true},{\"code\":\"404\",\"swap\":true,\"error\":true},{\"code\":\"409\",\"swap\":true,\"error\":true},{\"code\":\"5..\",\"swap\":true,\"error\":true},{\"code\":\"[45]..\",\"swap\":false,\"error\":true}]}'><script defer src=\"/static/js/alpinejs-3.16.1/cdn.min.js\"></script><style>\n\t\t[x-cloak] { display: none !important; }\n\t</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// baseURL is the browser-reachable origin (config server.base_url), used by the
// curl snippet so it stays honest behind a proxy or a non-default port.
func Index(baseURL string, total int64, mine int64) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<!doctype html><html lang=\"en\"><head>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = pageHead("GOTH template").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</head><body class=\"min-h-screen bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100\" x-data=\"{\n\t\t\t\tdarkMode: localStorage.getItem('theme') === 'dark',\n\t\t\t\ttoggleTheme() {\n\t\t\t\t\tthis.darkMode = !this.darkMode;\n\t\t\t\t\tlocalStorage.setItem('theme', this.darkMode ? 'dark' : 'light');\n\t\t\t\t\tdocument.documentElement.classList.toggle('dark', this.darkMode);\n\t\t\t\t}\n\t\t\t}\" x-init=\"document.documentElement.classList.toggle('dark', darkMode)\"><div class=\"min-h-screen flex items-center justify-center p-4\"><div class=\"w-full max-w-2xl bg-white dark:bg-gray-800 rounded-xl shadow-xl p-8\"><div class=\"flex items-start justify-between mb-6\"><div><h1 class=\"text-3xl font-bold\">Welcome to the GOTH template</h1><p class=\"text-gray-600 dark:text-gray-400 mt-1\">Go + Templ + HTMX + Tailwind, serving the same state over hypermedia (HDA) and JSON API.</p></div><button @click=\"toggleTheme()\" title=\"Toggle dark mode\" class=\"shrink-0 p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors\"><svg x-show=\"darkMode\" x-cloak class=\"h-5 w-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z\"></path></svg> <svg x-show=\"!darkMode\" class=\"h-5 w-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z\"></path></svg></button></div><div id=\"click-panel\" class=\"rounded-lg bg-gray-50 dark:bg-gray-900/50 p-6\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Click(total, mine).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"mt-4 flex flex-wrap items-center gap-3\"><button hx-post=\"/clicked\" hx-trigger=\"click\" hx-target=\"#click-panel-counts\" hx-swap=\"outerHTML\" hx-indicator=\"#click-spinner\" class=\"px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-md transition-colors\">Click to increment via HDA</button> <span id=\"click-spinner\" class=\"htmx-indicator\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.LoadingSpinner().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</span></div></div><div class=\"mt-6 text-sm text-gray-600 dark:text-gray-400 space-y-1\"><p>The same counter over JSON:</p><pre class=\"overflow-x-auto rounded bg-gray-100 dark:bg-gray-900 p-3 text-xs\"><code>curl ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(baseURL)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/index.templ`, Line: 86, Col: 104}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "/api/v1/clicks curl -X POST ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(baseURL)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/index.templ`, Line: 87, Col: 22}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "/api/v1/clicks/increment</code></pre><p>Also wired up: <a class=\"underline hover:no-underline\" href=\"/swagger/index.html\">/swagger</a>, <a class=\"underline hover:no-underline\" href=\"/readyz\">/readyz</a>, <a class=\"underline hover:no-underline\" href=\"/metrics\">/metrics</a>, <a class=\"underline hover:no-underline\" href=\"/ping\">/ping</a>.</p></div></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
